# Generated by Django 5.2.8 on 2025-12-10 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=64, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=256, null=True)),
                ('fecha', models.DateField()),
                ('foto', models.ImageField(upload_to='mascotas/')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.mascota')),
            ],
        ),
    ]
